{{- if and (hasKey .Values "image") (ne (default "" .Values.image.username) "") (ne (default "" .Values.image.password) "") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-insight-engine-image-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "insightengine.labels.standard" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "insightengine.imagePullSecret" . }}
{{- end }}
